# Generated by Django 5.1 on 2024-08-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('posting_time', models.DateTimeField()),
                ('receiving_time', models.DateTimeField()),
                ('text', models.TextField()),
                ('age', models.IntegerField()),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerpost.mail')),
            ],
        ),
    ]
