# Generated by Django 5.1 on 2024-08-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innerpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='age',
        ),
    ]
