# Generated by Django 5.1 on 2024-08-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerpost', '0002_remove_letter_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='last_uid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
